export const REFRESH_WIKI_PAGES = 'REFRESH_WIKI_PAGES'
export const UPDATE_WIKI_PAGE_DETAIL_STARTED = 'UPDATE_WIKI_PAGE_DETAIL_STARTED'
export const UPDATE_WIKI_PAGE_DETAIL_COMPLETED = 'UPDATE_WIKI_PAGE_DETAIL_COMPLETED'
