export const REFRESH_WIKI_PAGES = 'REFRESH_WIKI_PAGES'
export const UPDATE_WIKI_PAGE_DETAIL_STARTED = 'UPDATE_WIKI_PAGE_DETAIL_STARTED'
export const UPDATE_WIKI_PAGE_DETAIL_COMPLETED = 'UPDATE_WIKI_PAGE_DETAIL_COMPLETED'

export const ADD_TO_BOOKMARKS = 'ADD_TO_BOOKMARKS'
export const REMOVE_FROM_BOOKMARKS = 'REMOVE_FROM_BOOKMARKS'
